GUI rewrite and /ah search command
Crazy-Crew/CrazyAuctions pull request #143
Opened 2022-01-23 15:06 UTC by szumielxd

Just some changes for better optimization and future development:
- Replaced colllidable inventory title check with custom InventoryHolder. It should be faster and safer.
- Added command to filter items by name (`/ah search <phrase>`)
- Moved Methods#updateAuction file saving task to new thread. It should eliminate threadlocks on /ah command

2022-03-10 08:39 UTC, NoJokeFNA commented on src/main/java/me/badbones69/crazyauctions/api/enums/GuiType.java
> +	SEARCH(54, "Settings.Search", true),
Remove the last "," as it is useless

2022-03-10 08:39 UTC, NoJokeFNA commented on src/main/java/me/badbones69/crazyauctions/api/enums/GuiType.java
> +
Why sooo many empty lines tho?

2022-03-12 15:08 UTC, NoJokeFNA requested changes

2022-03-12 15:08 UTC, NoJokeFNA commented on src/main/java/me/badbones69/crazyauctions/Methods.java
> +        	new Thread(Files.DATA::saveFile, "Crazy-Auctions-Save-Task").start(); // save file in new thread
```suggestion
            new Thread(Files.DATA::saveFile, "Crazy-Auctions-Save-Task").start(); // save file in new thread
```
Code-Style..

2022-10-12 00:17 UTC, RyderBelserion commented
Closed pending re-write

2022-10-12 00:17 UTC, closed without merging